# Generated by Django 2.2.6 on 2019-11-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191120_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mock',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='refkey',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
