# Generated by Django 2.2.6 on 2019-11-21 10:58

from django.db import migrations, models
import names


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191120_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='name',
            field=models.CharField(default=names.get_full_name, max_length=100),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='stamp',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
