# Generated by Django 2.2.6 on 2019-11-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191121_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
