# Generated by Django 3.1.2 on 2020-11-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
