# Generated by Django 3.1.2 on 2020-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_auto_20201102_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
