# Generated by Django 3.1.2 on 2020-11-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20201102_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='mailed',
            field=models.BooleanField(default=False),
        ),
    ]
