# Generated by Django 3.1.2 on 2020-11-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20201102_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='refkey',
        ),
    ]
