# Generated by Django 3.1.2 on 2020-11-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201102_1006'),
        ('invitations', '0006_invitation_refkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='countries',
            field=models.ManyToManyField(related_name='invited_assignees', to='api.Country'),
        ),
    ]
