# Generated by Django 3.1.2 on 2020-11-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0008_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='message',
            field=models.TextField(default='[{{link}}](Click this link to participate)'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default='Invitation to participate in an expert survey', max_length=1024),
        ),
    ]
