# Generated by Django 3.1.2 on 2020-11-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201103_1328'),
        ('invitations', '0009_auto_20201104_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='active',
            field=models.BooleanField(default=False, help_text='Is template active? When sending mail, one of the active templates will be used. It is probably a good idea to only keep one template active.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_type',
            field=models.CharField(choices=[('inv', 'invitation'), ('rem', 'reminder')], default='inv', help_text='What kind of email is this? Determines when this email is sent.', max_length=3),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='message',
            field=models.TextField(default='[{{link}}](Click this link to participate)', help_text="Message-body of text. <a href='https://en.wikipedia.org/wiki/markdown' target='_blank'>Markdown formatted</a> Do not delete the weird-looking [{{link}}](click me) tag!"),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default='Invitation to participate in an expert survey', help_text='Subject-field of email', max_length=1024),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='countries',
            field=models.ManyToManyField(help_text='Countries that will be assigned to the user once they complete registration', related_name='invited_assignees', to='api.Country'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(help_text='Email to send invite to', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='mailed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Metadata that will be added to the user profile once they register. (occupation/sex/age/...) <a href='https://en.wikipedia.org/wiki/json' target='_blank'>JSON Formatted.</a>"),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='refkey',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
