# Generated by Django 3.1.2 on 2020-11-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0010_auto_20201104_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='active',
        ),
    ]
