# Generated by Django 3.1.2 on 2020-11-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0012_emailtemplate_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
