# Generated by Django 3.1.2 on 2020-11-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0013_auto_20201106_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='active',
            field=models.BooleanField(default=False, help_text='Is this model active? Only one model should be active.'),
        ),
    ]
