# Generated by Django 3.1.2 on 2020-11-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0014_auto_20201106_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='headline',
            field=models.CharField(default='Conflict Cartographer', help_text='Headline to display in the email', max_length=1024),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='htmlMessage',
            field=models.TextField(blank=True, editable=False, help_text='cached rendered HTML field', null=True),
        ),
    ]
