# Generated by Django 3.1.2 on 2020-11-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0015_auto_20201110_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='signature',
            field=models.TextField(default='The conflict cartographer team', help_text='The signature at the bottom of the email'),
        ),
    ]
