# Generated by Django 3.1.2 on 2020-11-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0016_emailtemplate_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='customemail',
            field=models.TextField(default='', help_text='A custom email text to send to this particular invitee. The text will be pasted into the standard email template, which includes the invitation link', verbose_name='Custom invitation email'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text="Metadata that will be added to the user profile once they register. (occupation/sex/age/...) <a href='https://en.wikipedia.org/wiki/json' target='_blank'>JSON Formatted.</a>"),
        ),
    ]
