# Generated by Django 3.1.2 on 2020-11-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0017_auto_20201119_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='customemail',
            field=models.TextField(blank=True, default='', help_text='A custom email text to send to this particular invitee. The text will be pasted into the standard email template, which includes the invitation link', verbose_name='Custom invitation email'),
        ),
    ]
