# Generated by Django 3.1.2 on 2020-11-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0020_auto_20201119_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='customsig',
            field=models.TextField(default='The Conflict Cartographer Team', help_text='A custom signature which will be displayed at the bottom of the email. The default is "The Conflict Cartographer Team".', verbose_name='Custom signature'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='customemail',
            field=models.TextField(blank=True, default='', help_text='A custom email text to send to this particular invitee. The text will be pasted into the standard email template, which includes the invitation link. If this field is left blank, the active email template will be used instead.', verbose_name='Custom invitation email'),
        ),
    ]
