# Generated by Django 3.1.2 on 2020-11-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0022_auto_20201120_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitedBy',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Invitation was sent by this user'),
        ),
    ]
