# Generated by Django 2.2.6 on 2020-09-11 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import names


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(default=names.get_full_name, max_length=100)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('refkey', models.CharField(max_length=32, unique=True)),
                ('reached', models.BooleanField(default=False)),
                ('opened', models.BooleanField(default=False)),
                ('registered', models.BooleanField(default=False)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.Cohort')),
                ('projects', models.ManyToManyField(related_name='projects', to='api.Project')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
