# Generated by Django 3.1.2 on 2020-11-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='assignees',
        ),
        migrations.AddField(
            model_name='profile',
            name='countries',
            field=models.ManyToManyField(related_name='assignees', to='api.Country'),
        ),
    ]
