# Generated by Django 3.1.2 on 2020-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201102_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
