# Generated by Django 3.1.2 on 2020-11-02 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201102_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='year',
        ),
        migrations.AddField(
            model_name='shape',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
