# Generated by Django 3.1.2 on 2020-11-03 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20201102_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso2c',
            field=models.CharField(default='AF', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='simpleshape',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='shape',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
