# Generated by Django 3.1.2 on 2020-11-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201103_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso2c',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
