# Generated by Django 3.1.2 on 2020-11-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(default='non'),
            preserve_default=False,
        ),
    ]
