# Generated by Django 3.1.2 on 2020-11-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201106_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdescription',
            name='active',
        ),
    ]
