# Generated by Django 3.1.2 on 2020-11-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_projectdescription_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdescription',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
