# Generated by Django 3.1.2 on 2020-11-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201113_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shapes', to='api.country'),
        ),
    ]
