# Generated by Django 3.1.2 on 2020-11-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201113_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonanswer',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shape',
            name='date',
            field=models.DateField(),
        ),
    ]
