# Generated by Django 3.1.2 on 2020-11-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_country_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='shape',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='shape',
            name='values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
