# Generated by Django 3.1.2 on 2022-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_shape_null_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_mailed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='unsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
