name: ci

on:
  push:
    branches: master

jobs:
  azure-acr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build and push
        uses: docker/build-push-action@v1
        with:
          repository: ccapp
          tags: latest
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.ACR_URL }}
