name: ci

on:
  push:
    branches: master

jobs:
  azure-acr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to ACR 
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./Dockerfile
          registry: ${{ secrets.ACR_URL }}
          tags: ccapp:latest
